### PR TITLE
modified wrapWithPromise code to eliminate error

### PR DESCRIPTION
**Pull request by mccallw23**
I believe this addresses one of the issues in the bugs channel.  Also, my bot has a weird behavior where it plays the first move in the game but won't play anymore.  I'm not using docker and `yarn build` in packages/bot compiles with no error.  I'm on a mac as well. Any ideas?

### CODE REVIEW

**Comment by scaljeri** [comment]
I tested you branch and also noticed that the if you use the webassembly stockfish, it only does one move. And that is because I have that first move hard coded :) Then, for that second move, Stofish throws an error

image

But, when I configure a pure backend engine, it works like a charm. It played a whole match

image

**Comment by mccallw23** [comment]
Hmmm, weird, when I switch to backend only and run 
`lerna run build` it builds fine, 
but running:
lerna run start` yields:

Screen Shot 2021-12-26 at 8 37 09 PM
I get an issue with a nonexistent directory. 

not sure if this is related, but my tsconfig.json is complaining about overwriting issues... 
Screen Shot 2021-12-26 at 8 45 34 PM
 Thank you for your help! excited to get this working!

**Comment by scaljeri** [comment]
I didn't run `lerna run start`, started the backend and frontend separately. So

    $> cd packages/engine
    $> npm run run:sf

and

   $> cd packages/bot
   $> npm start

Maybe that helps

**Comment by scaljeri** [comment]
I fixed the issue, it was an issue with SharedArrayBuffer. You can pull master!

**Comment by scaljeri** [comment]
Also, change your password for your chess.com account!!

**Comment by mccallw23** [comment]
pulling master changed password.  Thank you for the heads up. Will let you know what happens.

**Pull request merged**
